alarm_aggregator_node:
  ros__parameters:
    audio_base_dir: "audio"
    player_command: "aplay"
    fallback_player_command: "paplay"
    gas_audio: "gas_leak.wav"
    camera_audio: "temperature_anomaly.wav"
    alarm_category: ""
    play: false
